import { downloadBlob } from "./format";

// real File objects for documents uploaded this session (they can't be stored in localStorage)
export const fileBlobs = new Map();

const ascii = (s) => String(s).replace(/[^\x20-\x7E]/g, "?");

// a valid one-page PDF, so demo downloads open in any viewer
export function makeDemoPdf(title, lines) {
  const esc = (s) => ascii(s).replace(/[\\()]/g, "\\$&");
  const content = [
    `BT /F1 20 Tf 50 780 Td (${esc(title)}) Tj ET`,
    ...lines.map((l, i) => `BT /F1 11 Tf 50 ${745 - i * 20} Td (${esc(l)}) Tj ET`),
  ].join("\n");
  const objs = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>",
    `<< /Length ${content.length} >>\nstream\n${content}\nendstream`,
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
  ];
  let out = "%PDF-1.4\n";
  const offsets = [];
  objs.forEach((o, i) => {
    offsets.push(out.length);
    out += `${i + 1} 0 obj\n${o}\nendobj\n`;
  });
  const xref = out.length;
  out += `xref\n0 ${objs.length + 1}\n0000000000 65535 f \n`;
  out += offsets.map((o) => `${String(o).padStart(10, "0")} 00000 n \n`).join("");
  out += `trailer\n<< /Size ${objs.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;
  return new Blob([out], { type: "application/pdf" });
}

export function downloadDocument(doc, caseTitle) {
  const real = fileBlobs.get(doc.id);
  if (real) return downloadBlob(real, doc.name);

  const lines = [`Case: ${caseTitle}`, `Case No.: ${doc.caseNo}`, `Type: ${doc.type}`, `Added: ${doc.date} ${doc.time}`, `Uploaded by: ${doc.by}`, "", "This is a placeholder file generated by the LexPro demo."];
  const base = doc.name.replace(/\.[^.]+$/, "");
  if (doc.kind === "pdf") return downloadBlob(makeDemoPdf(doc.name, lines), doc.name);
  if (doc.kind === "sheet") return downloadBlob(new Blob([`Field,Value\nName,${doc.name}\nCase,${caseTitle}\nType,${doc.type}\n`], { type: "text/csv" }), `${base}.csv`);
  return downloadBlob(new Blob([`${doc.name}\n\n${lines.join("\n")}\n`], { type: "text/plain" }), `${base}.txt`);
}
